In [4]:
import torch
from torch import nn

In [18]:
# Shape : 2 x 3 x 4
# 3D Tensor
a = torch.rand(2, 3, 4)
a.size(1)
a

tensor([[[0.2267, 0.3553, 0.7998, 0.6171],
         [0.5699, 0.8799, 0.9625, 0.0814],
         [0.2660, 0.4023, 0.0990, 0.3036]],

        [[0.3236, 0.6281, 0.0048, 0.8061],
         [0.5077, 0.6297, 0.9064, 0.2436],
         [0.9855, 0.9147, 0.5387, 0.8139]]])

In [26]:
# dim == 0
# along dimension 0 --> a.size(0) == 2
# un fix dimension 0 and apply softmax for:
# a[0, 0 ,0]
# a[1, 0 ,0]
nn.functional.softmax(a, dim=0)

tensor([[[0.4758, 0.4322, 0.6889, 0.4529],
         [0.5155, 0.5622, 0.5140, 0.4595],
         [0.3275, 0.3746, 0.3918, 0.3751]],

        [[0.5242, 0.5678, 0.3111, 0.5471],
         [0.4845, 0.4378, 0.4860, 0.5405],
         [0.6725, 0.6254, 0.6082, 0.6249]]])

In [27]:
# dim == 1
# along dimension 1 --> a.size(0) == 3
# un fix dimension 1 and apply softmax for:
# a[0, 0 ,0]
# a[0, 1 ,0]
# a[0, 2 ,0]
nn.functional.softmax(a, dim=1)

tensor([[[0.2899, 0.2675, 0.3741, 0.4318],
         [0.4086, 0.4520, 0.4402, 0.2527],
         [0.3015, 0.2804, 0.1856, 0.3155]],

        [[0.2415, 0.3000, 0.1935, 0.3880],
         [0.2903, 0.3005, 0.4766, 0.2211],
         [0.4682, 0.3996, 0.3300, 0.3910]]])

In [29]:
# dim == 2
# along dimension 2 --> a.size(0) == 4
# un fix dimension 2 and apply softmax for:
# a[0, 0 ,0]
# a[0, 0 ,1]
# a[0, 0 ,2]
# a[0, 0 ,3]
nn.functional.softmax(a, dim=2)

tensor([[[0.1856, 0.2111, 0.3292, 0.2742],
         [0.2243, 0.3058, 0.3322, 0.1376],
         [0.2481, 0.2843, 0.2099, 0.2576]],

        [[0.2126, 0.2883, 0.1546, 0.3445],
         [0.2279, 0.2575, 0.3396, 0.1750],
         [0.2929, 0.2729, 0.1874, 0.2468]]])